import { createSavePointInteraction } from "../interactions.js";
import { TILE_IDS } from "../tiles.js";

export const TILE_EDITOR_META = {
    [TILE_IDS.STATION_FLOOR]: { label: "Station floor", category: "Ground" },
    [TILE_IDS.STATION_WALL]: { label: "Station wall", category: "Architecture" },
    [TILE_IDS.STATION_WATER]: { label: "Station water", category: "Ground" },
    [TILE_IDS.OFFICE_FLOOR]: { label: "Office floor", category: "Ground" },
    [TILE_IDS.OFFICE_WALL]: { label: "Office wall", category: "Architecture" },
    [TILE_IDS.OFFICE_WATER]: { label: "Office water", category: "Ground" },
    [TILE_IDS.ORCHARD_FLOOR]: { label: "Orchard floor", category: "Ground" },
    [TILE_IDS.ORCHARD_WALL]: { label: "Orchard wall", category: "Architecture" },
    [TILE_IDS.GLASS_FLOOR]: { label: "Glass floor", category: "Ground" },
    [TILE_IDS.SERVICE_FLOOR]: { label: "Service floor", category: "Ground" },
    [TILE_IDS.SERVICE_WALL]: { label: "Service wall", category: "Architecture" },
    [TILE_IDS.RED_FLOOR]: { label: "Red floor", category: "Ground" },
    [TILE_IDS.TRAIN_FLOOR]: { label: "Train floor", category: "Ground" },
    [TILE_IDS.TRAIN_WALL]: { label: "Train wall", category: "Architecture" },
    [TILE_IDS.TRACK_WATER]: { label: "Track water", category: "Ground" },
    [TILE_IDS.FINAL_FLOOR]: { label: "Final floor", category: "Ground" },
};

export const SPRITE_EDITOR_META = {
    "artificial-sun-changed": { label: "Artificial sun changed", category: "Quiet Line" },
    "artificial-sun": { label: "Artificial sun", category: "Quiet Line" },
    "attendant-0": { label: "Attendant 0", category: "Figures" },
    "attendant-1": { label: "Attendant 1", category: "Figures" },
    "attendant-2": { label: "Attendant 2", category: "Figures" },
    "attendant-3": { label: "Attendant 3", category: "Figures" },
    "bench": { label: "Bench", category: "Architecture" },
    "brass-tooth": { label: "Brass tooth", category: "Collectibles" },
    "cabinet-closed": { label: "Cabinet closed", category: "Architecture" },
    "cabinet-floating": { label: "Cabinet floating", category: "Architecture" },
    "camera-figure": { label: "Camera figure", category: "Figures" },
    "camera-number": { label: "Camera number", category: "Quiet Line" },
    "camera-platform": { label: "Camera platform", category: "Quiet Line" },
    "chair-facing": { label: "Chair facing", category: "Quiet Line" },
    "chair-out": { label: "Chair out", category: "Quiet Line" },
    "clock-down": { label: "Clock down", category: "Quiet Line" },
    "clock-empty": { label: "Clock empty", category: "Quiet Line" },
    "clock-one": { label: "Clock one", category: "Quiet Line" },
    "copier-duplicate": { label: "Copier duplicate", category: "Quiet Line" },
    "copier": { label: "Copier", category: "Quiet Line" },
    "desk": { label: "Desk", category: "Architecture" },
    "dry-chair": { label: "Dry chair", category: "Quiet Line" },
    "duplicate-player": { label: "Duplicate player", category: "Quiet Line" },
    "empty-seat": { label: "Empty seat", category: "Architecture" },
    "final-timetable": { label: "Final timetable", category: "Quiet Line" },
    "gate-apple": { label: "Gate apple", category: "Architecture" },
    "gate-blank": { label: "Gate blank", category: "Architecture" },
    "gate-eye": { label: "Gate eye", category: "Architecture" },
    "gate-umbrella": { label: "Gate umbrella", category: "Architecture" },
    "gate-zero": { label: "Gate zero", category: "Architecture" },
    "glass-figure": { label: "Glass figure", category: "Figures" },
    "glass-fruit": { label: "Glass fruit", category: "Collectibles" },
    "keyboard-moss": { label: "Keyboard moss", category: "Quiet Line" },
    "monitor-off": { label: "Monitor off", category: "Quiet Line" },
    "monitor-on": { label: "Monitor on", category: "Quiet Line" },
    "passenger-chair": { label: "Passenger chair", category: "Figures" },
    "passenger-signal": { label: "Passenger signal", category: "Figures" },
    "passenger-tree": { label: "Passenger tree", category: "Figures" },
    "picnic-blanket": { label: "Picnic blanket", category: "Quiet Line" },
    "platform-variation-a": { label: "Platform variation a", category: "Quiet Line" },
    "platform-variation-b": { label: "Platform variation b", category: "Quiet Line" },
    "punch-card": { label: "Punch card", category: "Collectibles" },
    "reflection-attendant": { label: "Reflection attendant", category: "Figures" },
    "reflection-backward": { label: "Reflection backward", category: "Figures" },
    "reflection-missing": { label: "Reflection missing", category: "Figures" },
    "reflection-normal": { label: "Reflection normal", category: "Figures" },
    "ringing-phone": { label: "Ringing phone", category: "Quiet Line" },
    "shelves": { label: "Shelves", category: "Architecture" },
    "sign-cleaning": { label: "Sign cleaning", category: "Quiet Line" },
    "sign-outside": { label: "Sign outside", category: "Quiet Line" },
    "sign-signal": { label: "Sign signal", category: "Quiet Line" },
    "sign-staff": { label: "Sign staff", category: "Quiet Line" },
    "signal-amber": { label: "Signal amber", category: "Quiet Line" },
    "signal-animal": { label: "Signal animal", category: "Figures" },
    "signal-apparatus-red": { label: "Signal apparatus red", category: "Quiet Line" },
    "signal-apparatus-white": { label: "Signal apparatus white", category: "Quiet Line" },
    "signal-dark": { label: "Signal dark", category: "Quiet Line" },
    "signal-red": { label: "Signal red", category: "Quiet Line" },
    "staff-door-locked": { label: "Staff door locked", category: "Architecture" },
    "staff-door-open": { label: "Staff door open", category: "Architecture" },
    "timetable-dark": { label: "Timetable dark", category: "Quiet Line" },
    "timetable-one": { label: "Timetable one", category: "Quiet Line" },
    "timetable-two": { label: "Timetable two", category: "Quiet Line" },
    "timetable-zero": { label: "Timetable zero", category: "Quiet Line" },
    "train-door": { label: "Train door", category: "Architecture" },
    "tree-awake": { label: "Tree awake", category: "Quiet Line" },
    "tree-sleep": { label: "Tree sleep", category: "Quiet Line" },
    "vending-0": { label: "Vending 0", category: "Quiet Line" },
    "vending-1": { label: "Vending 1", category: "Quiet Line" },
    "vending-2": { label: "Vending 2", category: "Quiet Line" },
    "vending-3": { label: "Vending 3", category: "Quiet Line" },
};

export const ENTITY_PRESETS = {
    blank: {
        label: "Blank entity",
        entity: { active: true, spriteId: "platform-variation-a", collision: false, interaction: null },
    },
    quietSaveBench: {
        label: "Quiet Line save bench",
        entity: {
            active: true,
            spriteId: "bench",
            collision: true,
            interaction: { handler: "effects", triggers: ["action"], effects: [{ type: "playSound", soundId: "save" }, { type: "saveGame" }] },
        },
    },
    timetable: {
        label: "Inspectable timetable",
        entity: { active: true, spriteId: "timetable-dark", collision: true, interaction: { handler: "effects", triggers: ["action"], effects: [{ type: "showText", pages: ["The timetable is warm."] }] } },
    },
};
